### PR TITLE
Add support for customRangeLabel prop

### PR DESCRIPTION
**Pull request by bghveding**
Hi,

I hope it's okay I opened a pull request. I've added a prop that let's you change the "Custom range" label, as this is something we need in our applications in order to translate it.

Thanks

### CODE REVIEW

**Comment by sharq1** [comment]
Hi @bghveding 
Sure it's ok :) 
Just fix that one thing I commented on and I'll merge it

**Comment by bghveding** [comment]
@sharq1 I cant' find any comments, am I blind? :)

**Comment by sharq1** [comment]
@bghveding sorry! I was commenting from mobile and did not notice that the review hasn't been sent...

**Comment by sharq1** [comment]
@bghveding I fixed that for you, it's published as 1.0.5

**Comment by bghveding** [comment]
@sharq1 Sorry about the typo! Thanks for fixing and merging so quickly :)

**Pull request merged**
